# Generated by Django 3.2 on 2021-04-06 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
