# Generated by Django 3.1.6 on 2021-05-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_homeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.homeinfo')),
            ],
        ),
    ]
