# Generated by Django 3.1.6 on 2021-05-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_homeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeImage',
        ),
    ]
