# Generated by Django 3.1.6 on 2021-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20210508_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
