# Generated by Django 3.1.6 on 2021-05-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20210508_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='author_image',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='image1',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
