# Generated by Django 3.1.6 on 2021-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, upload_to='images/gallery/'),
        ),
    ]
